In [1]:
import numpy as np

a = np.array([1,2,3,4,5])

a *= 10
a

array([10, 20, 30, 40, 50])

In [2]:
import numpy as np

a = np.array([1,3,5,7,9])
b = np.array([2,4,6,8,10])

a+b

array([ 3,  7, 11, 15, 19])

In [24]:
#2維ndarray
arr = np.array([[1, 3, 5 ],[2, 4, 6]])
arr.ndim #維度
arr.shape #形狀
arr.size #元素數量
arr.dtype #型別

dtype('int64')

In [36]:
np.random.rand()
np.random.rand(2,3)

array([[0.91939693, 0.26753477, 0.45118162],
       [0.5359976 , 0.19260086, 0.77214662]])

In [28]:
scores = np.random.randint(50, 101,size=(50,5))
scores

array([[ 60,  71,  50,  73,  99],
       [ 78,  98,  79,  73,  91],
       [ 93,  85,  95,  64,  87],
       [ 76,  64,  66,  54,  66],
       [ 81,  56,  95,  87,  80],
       [ 81,  68,  51,  83,  88],
       [ 54,  77,  87,  65,  86],
       [ 69,  56,  92,  95,  58],
       [ 56,  85,  63,  74,  81],
       [ 71,  63,  90,  59,  89],
       [ 75,  83,  56,  65,  52],
       [ 78,  90,  69,  80,  74],
       [ 99,  74,  59,  81,  78],
       [ 63,  59,  93,  83,  87],
       [ 63,  53,  77,  74,  74],
       [ 90,  93,  93,  73,  62],
       [100,  91,  94,  50,  88],
       [ 83,  85,  72,  82,  51],
       [ 71,  72,  96,  94,  63],
       [ 69,  65,  71,  65,  56],
       [ 70,  63,  86,  55,  54],
       [ 81,  71,  77,  59,  98],
       [ 53,  94,  67,  93,  75],
       [ 94,  95,  94,  76,  56],
       [ 70,  72,  88,  74,  98],
       [ 92,  97,  77,  69,  84],
       [ 77,  96,  64,  54,  57],
       [ 98,  54,  79,  82,  62],
       [ 89,  90,  75,  54,  52],
       [ 52,  