In [1]:
import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
#索引
arr[1]

#slice
arr[:5] #前5個
arr[3:] #最後5個

array([30, 40, 50, 60, 70, 80, 90])

In [6]:
scores = np.random.randint(50,101, size=(50, 5))
scores

array([[ 73,  71,  69,  59,  69],
       [ 98,  77,  61,  92,  88],
       [ 80,  84,  83,  73,  63],
       [ 53,  63,  74,  67,  57],
       [ 80,  61,  98,  76,  68],
       [ 64,  92, 100, 100,  63],
       [ 89,  61,  64,  74,  87],
       [ 98,  69,  66,  70,  90],
       [ 56,  54,  97,  63,  88],
       [ 95,  63,  54,  73,  53],
       [ 89,  60,  69,  51,  83],
       [ 78,  81,  85,  99,  82],
       [ 92,  79,  91,  71,  73],
       [ 60,  68,  88,  84,  60],
       [ 70,  74,  99,  67,  69],
       [ 74,  91,  79,  86,  67],
       [ 60,  65,  55,  72,  73],
       [ 99,  97,  80,  83,  82],
       [ 57,  95,  84,  73, 100],
       [ 94,  82,  55,  70,  99],
       [ 68,  69,  58,  74,  62],
       [ 64,  83,  82,  60,  81],
       [ 86,  86,  68,  86,  92],
       [ 74,  92,  77,  81,  64],
       [ 96,  89,  50,  66,  53],
       [ 75,  66,  53,  72,  85],
       [ 76,  57,  91,  94,  75],
       [ 98,  98,  58,  80,  81],
       [ 93,  66,  79,  87,  80],
       [ 75,  

In [16]:
#第一位學生的分數
scores[0] #(5,)
scores[0,:] #(5,)
scores[0:1,:] #(1, 5)

array([[73, 71, 69, 59, 69]], dtype=int32)

In [8]:
#前5位學生
scores[:5]
#前5位學生,前3個分數
scores[:5,:3]

array([[73, 71, 69],
       [98, 77, 61],
       [80, 84, 83],
       [53, 63, 74],
       [80, 61, 98]], dtype=int32)

In [9]:
#第1科分數
scores[:,0]
scores[:,1]
scores[:,2]

array([ 69,  61,  83,  74,  98, 100,  64,  66,  97,  54,  69,  85,  91,
        88,  99,  79,  55,  80,  84,  55,  58,  82,  68,  77,  50,  53,
        91,  58,  79,  72,  71,  59,  74,  74,  52,  68,  71,  82,  96,
        71,  64,  71,  71,  94,  80,  87,  82,  82,  71,  66], dtype=int32)

In [10]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([341, 416, 383, 314, 383, 419, 375, 393, 358, 338, 352, 425, 406,
       360, 379, 397, 325, 441, 409, 400, 331, 370, 418, 388, 354, 351,
       393, 415, 405, 347, 417, 364, 398, 336, 339, 396, 383, 373, 419,
       370, 405, 421, 375, 370, 359, 389, 377, 398, 390, 346], dtype=int32)

In [11]:
#算出均分
total / 5

array([68.2, 83.2, 76.6, 62.8, 76.6, 83.8, 75. , 78.6, 71.6, 67.6, 70.4,
       85. , 81.2, 72. , 75.8, 79.4, 65. , 88.2, 81.8, 80. , 66.2, 74. ,
       83.6, 77.6, 70.8, 70.2, 78.6, 83. , 81. , 69.4, 83.4, 72.8, 79.6,
       67.2, 67.8, 79.2, 76.6, 74.6, 83.8, 74. , 81. , 84.2, 75. , 74. ,
       71.8, 77.8, 75.4, 79.6, 78. , 69.2])

In [ ]:
#np內的function
np.sum(scores,axis=1)
np.mean(scores,axis=1)

array([68.2, 83.2, 76.6, 62.8, 76.6, 83.8, 75. , 78.6, 71.6, 67.6, 70.4,
       85. , 81.2, 72. , 75.8, 79.4, 65. , 88.2, 81.8, 80. , 66.2, 74. ,
       83.6, 77.6, 70.8, 70.2, 78.6, 83. , 81. , 69.4, 83.4, 72.8, 79.6,
       67.2, 67.8, 79.2, 76.6, 74.6, 83.8, 74. , 81. , 84.2, 75. , 74. ,
       71.8, 77.8, 75.4, 79.6, 78. , 69.2])

In [18]:
#實體方法
scores.sum(axis=1)
scores.mean(axis=1)

array([68.2, 83.2, 76.6, 62.8, 76.6, 83.8, 75. , 78.6, 71.6, 67.6, 70.4,
       85. , 81.2, 72. , 75.8, 79.4, 65. , 88.2, 81.8, 80. , 66.2, 74. ,
       83.6, 77.6, 70.8, 70.2, 78.6, 83. , 81. , 69.4, 83.4, 72.8, 79.6,
       67.2, 67.8, 79.2, 76.6, 74.6, 83.8, 74. , 81. , 84.2, 75. , 74. ,
       71.8, 77.8, 75.4, 79.6, 78. , 69.2])